apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-gettingstarted-deployment
  namespace: oke1
spec:
  selector:
    matchLabels:
      app: node-gettingstarted
  replicas: 3
  template:
    metadata:
      labels:
        app: node-gettingstarted
    spec:
      containers:
        - name: node-gettingstarted
          # enter the path to your image, be sure to include the correct region prefix
          image: iad.ocir.io/sehubjapacprod/ocidevopsoke/nodejs:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
      imagePullSecrets:
        - name: ocirsecret        
---
apiVersion: v1
kind: Service
metadata:
  name: node-gettingstarted-service
  namespace: oke1
  annotations: 
    service.beta.kubernetes.io/oci-load-balancer-shape: "10Mbps"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: node-gettingstarted
